### ISSUE TITLE
YuniKorn not able to schedule resources while kube default is able to

### ISSUE THREAD

**Issue by abhranilc** [cloudera/yunikorn-k8shim#42] opened 2019-09-06 05:08 UTC
When Scale up of an nginx deployment is done to an extent when available resources fall short (7 in my case), some pods remain in pending state (1 in my case, 6 pods are running). If then, the deployment is scaled down to 4 pods, deployment shows 4/4 running as expected. But now I cannot scale it back to 6 pods (while previously 6/7 pods were running). If I do a fresh deployment in another queue, still same issue persists. However, if I remove "schedulerName: yunikorn" from the nginx deployment and re deploy nginx, I get upto 2/2 pods running, i.e. 6 pods in all across the 2 deployments.

Please find my environment and configurations below to reproduce the problem:
<img width="588" alt="p1" src="https://user-images.githubusercontent.com/3633725/64402378-59171b80-d092-11e9-809c-7c34be56aa12.png">
<img width="503" alt="p2" src="https://user-images.githubusercontent.com/3633725/64402379-5caaa280-d092-11e9-9516-65e7f7436804.png">
<img width="431" alt="p3" src="https://user-images.githubusercontent.com/3633725/64402381-603e2980-d092-11e9-8f94-a23775bfa309.png">
<img width="364" alt="p4" src="https://user-images.githubusercontent.com/3633725/64402394-692efb00-d092-11e9-9448-95d5c65829ec.png">

**Comment by abhranilc** [comment] 2019-09-06 05:10
<img width="1383" alt="p5" src="https://user-images.githubusercontent.com/3633725/64402442-9a0f3000-d092-11e9-81fd-0cb4981a832b.png">
<img width="1417" alt="p6" src="https://user-images.githubusercontent.com/3633725/64402445-9d0a2080-d092-11e9-8b43-d2ff7304de5e.png">
<img width="1181" alt="p7" src="https://user-images.githubusercontent.com/3633725/64402450-a5625b80-d092-11e9-9c0a-6fb56373c2c0.png">
<img width="1378" alt="p8" src="https://user-images.githubusercontent.com/3633725/64402455-a85d4c00-d092-11e9-8a1c-865474693392.png">
<img width="1421" alt="p9" src="https://user-images.githubusercontent.com/3633725/64402460-ad220000-d092-11e9-8f04-e8b037407af8.png">
<img width="1218" alt="p10" src="https://user-images.githubusercontent.com/3633725/64402461-b14e1d80-d092-11e9-8b00-b0a05e2d8832.png">
<img width="1413" alt="p11" src="https://user-images.githubusercontent.com/3633725/64402462-b612d180-d092-11e9-8468-21a1ca0a6fd3.png">
<img width="1381" alt="p12" src="https://user-images.githubusercontent.com/3633725/64402465-bad78580-d092-11e9-92b6-198fbcf64a0f.png">
<img width="1421" alt="p13" src="https://user-images.githubusercontent.com/3633725/64402469-be6b0c80-d092-11e9-9477-296b65fe9789.png">
<img width="1433" alt="p14" src="https://user-images.githubusercontent.com/3633725/64402475-c1fe9380-d092-11e9-9f8b-7c44b31373a1.png">

**Comment by yangwwei** [comment] 2019-09-09 09:58
Thanks @abhranilc  for the detail instructions. It really helps. 
I was able to reproduce the same issue on my local environment. So what happens was:

internally, yunikorn-shim re-uses some code from default scheduler specifically for predicates, as a plugin. this is because we need to support all predicates currently available in K8s. when we place a pod to a node, we first assume the pod will be running on that node (cached data), that way we can evaluate some predicate rules during the allocation process. 

So when we do allocations, it will be some pods be "assumed" in the cache, however, current code forgets to remove them when releasing allocations. This causes the issue, even allocations are correct in the scheduler, the cached data was out-of-sync. so when you want to scale up again, it complains the predicate rule is failing.

I will provide a fix soon. Thanks for catching up this issue.

**Comment by yangwwei** [comment] 2019-09-10 04:05
this should be fixed now, @abhranilc pls try out when you get some time.

**Closed by yangwwei** 2019-09-10 04:05 UTC
Labels: bug
